[package]
name = "calculator"
version = "0.2.0"
authors = ["Abhishek Sathiabalan", "Balaji Sivaraman <balaji@balajisivaraman.com>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
nom = "6"
